-- Space Client: persistent accounts storage in Supabase
-- Run this once in Supabase Dashboard -> SQL Editor.

create table if not exists public.accounts (
  email text primary key,
  nick text not null,
  nick_normalized text not null unique,
  password_hash text not null,
  balance bigint not null default 0,
  banned boolean not null default false,
  plan text not null default 'none',
  expires timestamptz,
  registered_at timestamptz not null default now(),
  last_seen timestamptz
);

create index if not exists accounts_nick_normalized_idx
  on public.accounts (nick_normalized);

alter table public.accounts enable row level security;

-- The site accesses this table only from the Layero backend with the
-- Supabase secret/service-role key. Do not expose that key in the browser.
revoke all on table public.accounts from anon, authenticated;

comment on table public.accounts is
  'Space Client accounts. Accessed by the Layero backend only.';


-- Compatibility fixes for an existing accounts table:
-- registration must never send NULL into the required plan column.
alter table public.accounts alter column plan set default 'none';
update public.accounts set plan = 'none' where plan is null;
alter table public.accounts alter column plan set not null;

-- Online/offline activity timestamp. Existing accounts start without a last-seen value.
alter table public.accounts add column if not exists last_seen timestamptz;


-- Admin permissions for player management.
alter table public.accounts add column if not exists is_admin boolean not null default false;
update public.accounts set is_admin = true where lower(nick) = 'winzuxx';


-- Persistent sessions: survive Layero runtime restarts/redeploys and browser restarts.
-- The raw session token is never stored in Supabase; only its SHA-256 hash is stored.
create table if not exists public.sessions (
  token_hash text primary key,
  email text not null,
  nick text not null,
  kind text not null check (kind in ('user','admin')),
  created_at timestamptz not null default now()
);

create index if not exists sessions_email_idx on public.sessions (email);
create index if not exists sessions_kind_idx on public.sessions (kind);

alter table public.sessions enable row level security;
revoke all on table public.sessions from anon, authenticated;

comment on table public.sessions is
  'Persistent Space Client sessions. Accessed only by the Layero backend with the Supabase secret/service-role key.';


-- Server activity monitor logs.
create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  ip text not null,
  nick text,
  action text not null,
  details text,
  created_at timestamptz not null default now()
);
create index if not exists activity_logs_created_idx on public.activity_logs (created_at desc);
alter table public.activity_logs enable row level security;
revoke all on table public.activity_logs from anon, authenticated;


-- Admin device/activity details. These fields store only the latest client metadata.
alter table public.accounts add column if not exists last_ip text;
alter table public.accounts add column if not exists last_user_agent text;
alter table public.accounts add column if not exists last_device text;
alter table public.accounts add column if not exists last_screen_width integer;
alter table public.accounts add column if not exists last_screen_height integer;
alter table public.accounts add column if not exists last_screen_dpr numeric(4,2);

alter table public.activity_logs add column if not exists user_agent text;
alter table public.activity_logs add column if not exists device text;
alter table public.activity_logs add column if not exists screen_width integer;
alter table public.activity_logs add column if not exists screen_height integer;

-- Friends, friend requests and private chat.
create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  requester_email text not null,
  addressee_email text not null,
  status text not null default 'pending' check (status in ('pending','accepted','rejected')),
  created_at timestamptz not null default now(),
  responded_at timestamptz,
  constraint friend_requests_not_self check (lower(requester_email) <> lower(addressee_email))
);
create index if not exists friend_requests_addressee_idx on public.friend_requests (addressee_email, status, created_at desc);
create index if not exists friend_requests_requester_idx on public.friend_requests (requester_email, status, created_at desc);
alter table public.friend_requests enable row level security;
revoke all on table public.friend_requests from anon, authenticated;

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  user_a_email text not null,
  user_b_email text not null,
  created_at timestamptz not null default now(),
  constraint friendships_not_self check (lower(user_a_email) <> lower(user_b_email)),
  constraint friendships_pair_unique unique (user_a_email, user_b_email)
);
create index if not exists friendships_a_idx on public.friendships (user_a_email);
create index if not exists friendships_b_idx on public.friendships (user_b_email);
alter table public.friendships enable row level security;
revoke all on table public.friendships from anon, authenticated;

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_email text not null,
  receiver_email text not null,
  body text not null,
  created_at timestamptz not null default now(),
  constraint messages_not_self check (lower(sender_email) <> lower(receiver_email)),
  constraint messages_body_length check (char_length(body) between 1 and 2000)
);
create index if not exists messages_pair_idx on public.messages (sender_email, receiver_email, created_at);
create index if not exists messages_receiver_idx on public.messages (receiver_email, created_at desc);
alter table public.messages enable row level security;
revoke all on table public.messages from anon, authenticated;


-- Read state for messenger unread counters.
alter table public.messages add column if not exists read_at timestamptz;
create index if not exists messages_unread_idx on public.messages (receiver_email, read_at) where read_at is null;

-- IMPORTANT: current server no longer requires public.friendships.
-- Accepted rows in public.friend_requests are used as the friendship relation.
-- This avoids failures on installations where the friendships table was never created.


-- Fast online presence. true while the browser sends a 5-second heartbeat.
alter table public.accounts add column if not exists is_online boolean not null default false;
create index if not exists accounts_online_idx on public.accounts (is_online, last_seen desc);

-- Messenger edit/delete state.
alter table public.messages add column if not exists edited_at timestamptz;
alter table public.messages add column if not exists deleted_at timestamptz;

-- Messenger emoji reactions.
create table if not exists public.message_reactions (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.messages(id) on delete cascade,
  email text not null,
  emoji text not null,
  created_at timestamptz not null default now(),
  constraint message_reactions_emoji check (emoji in ('❤️','😂','😍','😮','😢','👍','🔥','🎉')),
  constraint message_reactions_unique unique (message_id, email, emoji)
);
create index if not exists message_reactions_message_idx on public.message_reactions(message_id);
alter table public.message_reactions enable row level security;
revoke all on table public.message_reactions from anon, authenticated;

-- Payments / balance top-ups.
-- The Layero backend creates orders and credits balance only after the external
-- payment provider confirms the payment. Card data never touches Space Client.
create table if not exists public.payment_orders (
  order_id text primary key,
  email text not null,
  amount bigint not null check (amount >= 10 and amount <= 1000000),
  currency text not null default 'RUB',
  provider text not null check (provider in ('yookassa','cryptomus')),
  method text not null check (method in ('card','sbp','crypto')),
  provider_payment_id text,
  status text not null default 'pending',
  error_message text,
  credited_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists payment_orders_email_idx on public.payment_orders(email, created_at desc);
create index if not exists payment_orders_provider_id_idx on public.payment_orders(provider, provider_payment_id);
alter table public.payment_orders enable row level security;
revoke all on table public.payment_orders from anon, authenticated;

-- Atomic balance credit used only after a provider has confirmed a payment.
-- This prevents a webhook + status-poll race from crediting the same order twice.
create or replace function public.credit_payment_order(p_order_id text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text;
  v_amount bigint;
  v_credited timestamptz;
  v_balance bigint;
begin
  select email, amount, credited_at
    into v_email, v_amount, v_credited
    from public.payment_orders
   where order_id = p_order_id
   for update;

  if not found then
    raise exception 'Payment order not found';
  end if;

  if v_credited is not null then
    select balance into v_balance from public.accounts where lower(email)=lower(v_email);
    return coalesce(v_balance, 0);
  end if;

  update public.accounts
     set balance = balance + v_amount
   where lower(email)=lower(v_email)
   returning balance into v_balance;

  if not found then
    raise exception 'Account not found';
  end if;

  update public.payment_orders
     set status = 'credited', credited_at = now(), updated_at = now()
   where order_id = p_order_id;

  return v_balance;
end;
$$;

revoke all on function public.credit_payment_order(text) from public;
grant execute on function public.credit_payment_order(text) to service_role;

-- Space Client Windows Launcher: one-time browser -> launcher login tickets.
-- ticket_value is short-lived (2 minutes) and is deleted immediately after exchange.
create table if not exists public.launcher_tickets (
  id bigint generated by default as identity primary key,
  ticket_hash text not null unique,
  token_hash text not null,
  token_value text not null,
  email text not null,
  nick text not null,
  nonce text not null,
  callback_url text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
create index if not exists launcher_tickets_expires_idx on public.launcher_tickets(expires_at);
alter table public.launcher_tickets enable row level security;
revoke all on table public.launcher_tickets from anon, authenticated;

-- Password-reset codes and resend cooldowns.
-- The Cloudflare Worker (worker.js) has no long-lived in-memory process like
-- the old Node server did, so this state now lives in Supabase instead of a
-- JS Map. One row per email holds both the active code and the cooldown.
create table if not exists public.password_resets (
  email text primary key,
  code text,
  code_expires_at timestamptz,
  verified_token text,
  verified_token_expires_at timestamptz,
  next_allowed_at timestamptz,
  next_delay_seconds integer not null default 60,
  updated_at timestamptz not null default now()
);
alter table public.password_resets enable row level security;
revoke all on table public.password_resets from anon, authenticated;
comment on table public.password_resets is
  'Password-reset codes/cooldowns. Accessed only by the Worker with the Supabase secret/service-role key.';
